-- book-collection database schema
--
-- This file described the original MySQL schema and is kept only as a
-- pointer for anyone who finds it by its old name - the database was
-- migrated from MySQL to PostgreSQL in May 2026 (see
-- database/migrate_mysql_to_postgres.py) and this file is no longer run
-- against anything.
--
-- For the current PostgreSQL schema, use one of:
--   database/schema_current.sql   - canonical schema for a fresh install
--                                    (run via database/setup_db.py)
--   database/schema_postgres.sql  - incremental schema for an existing,
--                                    already-migrated database
--   database/add_pgvector.sql     - RAG/pgvector addition (already folded
--                                    into schema_current.sql)
--
-- schema.json and schema.yaml in this directory are kept in sync with the
-- current PostgreSQL structure and can be used as a machine-readable
-- reference.
