services:
  book-service:
    restart: unless-stopped
    image: localhost:5000/book-service:latest
    container_name: book-service
    environment:
      - API_KEY=${API_KEY}
      - AI_EMBED_HOST=${AI_EMBED_HOST}
      - AI_EMBED_MODEL=${AI_EMBED_MODEL}
      - AI_EMBED_API_KEY=${AI_EMBED_API_KEY}
      - AI_EMBED_DIMENSIONS=${AI_EMBED_DIMENSIONS}
    volumes:
      - /var/www/html/resources/books:/books/uploads
    ports:
      - 8084:8084
    extra_hosts:
      - host.docker.internal:host-gateway
networks: {}